# Generated by Django 5.0 on 2023-12-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
